// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// c_s_h
double c_s_h(double t, double h);
RcppExport SEXP cgAUC_c_s_h(SEXP tSEXP, SEXP hSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< double >::type t(tSEXP );
        Rcpp::traits::input_parameter< double >::type h(hSEXP );
        double __result = c_s_h(t, h);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// c_dscrt
/* theta_sh_0 */ NumericVector c_dscrt(NumericMatrix y, NumericVector z, NumericVector l);
RcppExport SEXP cgAUC_c_dscrt(SEXP ySEXP, SEXP zSEXP, SEXP lSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type l(lSEXP );
        /* theta_sh_0 */ NumericVector __result = c_dscrt(y, z, l);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// c_cntin
/*  theta_sh */ NumericVector c_cntin(NumericMatrix y, NumericVector z, NumericVector l, double h);
RcppExport SEXP cgAUC_c_cntin(SEXP ySEXP, SEXP zSEXP, SEXP lSEXP, SEXP hSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type l(lSEXP );
        Rcpp::traits::input_parameter< double >::type h(hSEXP );
        /*  theta_sh */ NumericVector __result = c_cntin(y, z, l, h);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// c_d_theta_sh_h_p
/* step 1 */ NumericVector c_d_theta_sh_h_p(NumericMatrix y, NumericVector z, NumericVector l, double h);
RcppExport SEXP cgAUC_c_d_theta_sh_h_p(SEXP ySEXP, SEXP zSEXP, SEXP lSEXP, SEXP hSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type l(lSEXP );
        Rcpp::traits::input_parameter< double >::type h(hSEXP );
        /* step 1 */ NumericVector __result = c_d_theta_sh_h_p(y, z, l, h);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
